# Generated by Django 2.2.25 on 2021-12-30 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
