# Generated by Django 2.2.25 on 2021-12-30 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20211230_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
