# Generated by Django 2.2.25 on 2021-12-30 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20211230_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
